name: Flutter - build apk and app bundle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
        # run all of the following commands in disaster_relief_aid_flutter directory
        working-directory: disaster_relief_aid_flutter
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
