name: Release - build apk and app bundle
on:
  push:
    tags:
      - "*"
  pull_request:
    tags:
      - "*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: disaster_relief_aid_flutter

    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

  
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: do flutter stuff
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"


      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99+99/'$RELEASE_VERSION'/g' pubspec.yaml|
          echo "Tag used version:"$RELEASE_VERSION

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # delete the existing tag
      - name: Delete tag
        run: git push --delete origin ${{ steps.vars.outputs.tag }}

      # create the new release tag
      - name: automatic release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.vars.outputs.tag }}
          prerelease: false
          files: |
            LICENSE.txt
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
